### ISSUE TITLE
Request: Add "Nut Roast" menu item to the mod if possible?

### ISSUE THREAD

**Issue by D3FAU4T** [propstg/plateup-starting-meal-selector#3]
Is it possible to add the "Nut Roast" menu item in the mod menu? I believe it was a part of the halloween update, it came with the "Turkey".

**Comment by propstg** [comment]
Looks like it. I haven't tested it thoroughly, but I was able to start a restaurant with it and play a day. I didn't even know this main existed, lol.

**Comment by propstg** [comment]
This has been released on the workshop

**Comment by D3FAU4T** [comment]
Thank you for taking the request into consideration. I'm already a JavaScript and TypeScript developer and I learned C# yesterday from tutorials just to make mods for the PlateUp game lol. So as a C# beginner, is it possible that I can download your code and keep it as a "guide reference" of the modules and data structures to learn so I can improve in coding C# for the PlateUp mods?

**Comment by propstg** [comment]
Of course! If you're not there already, you might want to consider joining the [Unofficial PlateUp Modding Discord](https://discord.gg/uPbuYVjJQq). They're very friendly and helpful over there. :)

**Comment by D3FAU4T** [comment]
Thank you!
